using System.Collections.Generic;

public static class TeraTypeDictionaries
{
    public static readonly Dictionary<string, string> TeraEmojis = new Dictionary<string, string>
    {
        { "Normal", "<:Normal:1134575677648162886>" },
        { "Fire", "<:Fire:1134576993799766197>" },
        { "Water", "<:Water:1134575004038742156>" },
        { "Grass", "<:Grass:1134574800057139331>" },
        { "Flying", "<:Flying:1134573296734711918>" },
        { "Poison", "<:Poison:1134575188403564624>" },
        { "Electric", "<:Electric:1134576561991995442>" },
        { "Ground", "<:Ground:1134573701766058095>" },
        { "Psychic", "<:Psychic:1134576746298089575>" },
        { "Fighting", "<:Fighting:1134573062881300551>" },
        { "Rock", "<:Rock:1134574024542912572>" },
        { "Ice", "<:Ice:1134576183787409531>" },
        { "Bug", "<:Bug:1134574602908073984>" },
        { "Dragon", "<:Dragon:1134576015973294221>" },
        { "Ghost", "<:Ghost:1134574276628975626>" },
        { "Dark", "<:Dark:1134575488598294578>" },
        { "Steel", "<:Steel:1134576384191254599>" },
        { "Fairy", "<:Fairy:1134575841523814470>" },
        { "Stellar", "<:Stellar:1186199337177468929>" },
    };

    public static readonly Dictionary<string, string> TeraTranslations = new Dictionary<string, string>
    {
        { "Normal", "Normal" },
        { "Fire", "Fuego" },
        { "Water", "Agua" },
        { "Grass", "Planta" },
        { "Electric", "Eléctrico" },
        { "Ice", "Hielo" },
        { "Fighting", "Lucha" },
        { "Poison", "Veneno" },
        { "Ground", "Tierra" },
        { "Flying", "Volador" },
        { "Psychic", "Psíquico" },
        { "Bug", "Bicho" },
        { "Rock", "Roca" },
        { "Ghost", "Fantasma" },
        { "Dragon", "Dragón" },
        { "Dark", "Siniestro" },
        { "Steel", "Acero" },
        { "Fairy", "Hada" },
        { "Stellar", "Estelar" }
    };
}

public static class NatureTranslations
{
    public static readonly Dictionary<string, string> TraduccionesNaturalezas = new Dictionary<string, string>
    {
        { "Hardy", "Fuerte" },
        { "Lonely", "Huraña" },
        { "Brave", "Audaz" },
        { "Adamant", "Firme" },
        { "Naughty", "Pícara" },
        { "Bold", "Osada" },
        { "Docile", "Dócil" },
        { "Relaxed", "Plácida" },
        { "Impish", "Agitada" },
        { "Lax", "Floja" },
        { "Timid", "Miedosa" },
        { "Hasty", "Activa" },
        { "Serious", "Seria" },
        { "Jolly", "Alegre" },
        { "Naive", "Ingenua" },
        { "Modest", "Modesta" },
        { "Mild", "Afable" },
        { "Quiet", "Mansa" },
        { "Bashful", "Tímida" },
        { "Rash", "Alocada" },
        { "Calm", "Serena" },
        { "Gentle", "Amable" },
        { "Sassy", "Grosera" },
        { "Careful", "Cauta" },
        { "Quirky", "Rara" }
    };
}

public static class ScaleEmojisDictionary
{
    public static readonly Dictionary<string, string> ScaleEmojis = new Dictionary<string, string>
    {
        { "XXXS", "<:minimark:1158632782013136946>" }, // Emoji para XXXS
        { "XXXL", "<:jumbomark:1158632783380492318>" }  // Emoji para XXXL
    };
}

public static class AbilityTranslationDictionary
{
    public static readonly Dictionary<string, string> AbilityTranslation = new Dictionary<string, string>
    {
        { "Stench", "Hedor" },
        { "Drizzle", "Llovizna" },
        { "Speed Boost", "Impulso" },
        { "Battle Armor", "Armadura Batalla" },
        { "Sturdy", "Robustez" },
        { "Damp", "Humedad" },
        { "Limber", "Flexibilidad" },
        { "Sand Veil", "Velo Arena" },
        { "Static", "Elec. Estática" },
        { "Volt Absorb", "Absorbe Elec" },
        { "Water Absorb", "Absorbe Agua" },
        { "Oblivious", "Despiste" },
        { "Cloud Nine", "Aclimatación" },
        { "Compound Eyes", "Ojo Compuesto" },
        { "Insomnia", "Insomnio" },
        { "Color Change", "Cambio Color" },
        { "Immunity", "Inmunidad" },
        { "Flash Fire", "Absorbe Fuego" },
        { "Shield Dust", "Polvo Escudo" },
        { "Own Tempo", "Ritmo Propio" },
        { "Suction Cups", "Ventosas" },
        { "Intimidate", "Intimidación" },
        { "Shadow Tag", "Sombra Trampa" },
        { "Rough Skin", "Piel Tosca" },
        { "Wonder Guard", "Superguarda" },
        { "Levitate", "Levitación" },
        { "Effect Spore", "Efecto Espora" },
        { "Synchronize", "Sincronía" },
        { "Clear Body", "Cuerpo Puro" },
        { "Natural Cure", "Cura Natural" },
        { "Lightning Rod", "Pararrayos" },
        { "Serene Grace", "Dicha" },
        { "Swift Swim", "Nado Rápido" },
        { "Chlorophyll", "Clorofila" },
        { "Illuminate", "Iluminación" },
        { "Trace", "Rastro" },
        { "Huge Power", "Potencia" },
        { "Poison Point", "Punto Tóxico" },
        { "Inner Focus", "Foco Interno" },
        { "Magma Armor", "Escudo Magma" },
        { "Water Veil", "Velo Agua" },
        { "Magnet Pull", "Imán" },
        { "Soundproof", "Insonorizar" },
        { "Rain Dish", "Cura Lluvia" },
        { "Sand Stream", "Chorro Arena" },
        { "Pressure", "Presión" },
        { "Thick Fat", "Sebo" },
        { "Early Bird", "Madrugar" },
        { "Flame Body", "Cuerpo Llama" },
        { "Run Away", "Fuga" },
        { "Keen Eye", "Vista Lince" },
        { "Hyper Cutter", "Corte Fuerte" },
        { "Pickup", "Recogida" },
        { "Truant", "Ausente" },
        { "Hustle", "Entusiasmo" },
        { "Cute Charm", "Gran Encanto" },
        { "Plus", "Más" },
        { "Minus", "Menos" },
        { "Forecast", "Predicción" },
        { "Sticky Hold", "Viscosidad" },
        { "Shed Skin", "Mudar" },
        { "Guts", "Agallas" },
        { "Marvel Scale", "Escama Especial" },
        { "Liquid Ooze", "Lodo Líquido" },
        { "Overgrow", "Espesura" },
        { "Blaze", "Mar Llamas" },
        { "Torrent", "Torrente" },
        { "Swarm", "Enjambre" },
        { "Rock Head", "Cabeza Roca" },
        { "Drought", "Sequía" },
        { "Arena Trap", "Trampa Arena" },
        { "Vital Spirit", "Espíritu Vital" },
        { "White Smoke", "Humo Blanco" },
        { "Pure Power", "Energía pura" },
        { "Shell Armor", "Caparazón" },
        { "Cacophony", "Cacofonía" },
        { "Air Lock", "Bucle Aire" },
        { "Tangled Feet", "Tumbos" },
        { "Motor Drive", "Electromotor" },
        { "Rivalry", "Rivalidad" },
        { "Steadfast", "Impasible" },
        { "Snow Cloak", "Manto Níveo" },
        { "Gluttony", "Gula" },
        { "Anger Point", "Irascible" },
        { "Unburden", "Liviano" },
        { "Heatproof", "Ignífugo" },
        { "Simple", "Simple" },
        { "Dry Skin", "Piel Seca" },
        { "Download", "Descarga" },
        { "Iron Fist", "Puño Férreo" },
        { "Poison Heal", "Antídoto" },
        { "Adaptability", "Adaptable" },
        { "Skill Link", "Encadenado" },
        { "Hydration", "Hidratación" },
        { "Solar Power", "Poder Solar" },
        { "Quick Feet", "Pies Rápidos" },
        { "Normalize", "Normalidad" },
        { "Sniper", "Francotirador" },
        { "Magic Guard", "Muro Mágico" },
        { "No Guard", "Indefenso" },
        { "Stall", "Rezagado" },
        { "Technician", "Experto" },
        { "Leaf Guard", "Defensa Hoja" },
        { "Klutz", "Zoquete" },
        { "Mold Breaker", "Rompemoldes" },
        { "Super Luck", "Afortunado" },
        { "Aftermath", "Resquicio" },
        { "Anticipation", "Anticipación" },
        { "Forewarn", "Alerta" },
        { "Unaware", "Ignorante" },
        { "Tinted Lens", "Cromolente" },
        { "Filter", "Filtro" },
        { "Slow Start", "Inicio Lento" },
        { "Scrappy", "Intrépido" },
        { "Storm Drain", "Colector" },
        { "Ice Body", "Gélido" },
        { "Solid Rock", "Roca Sólida" },
        { "Snow Warning", "Nevada" },
        { "Honey Gather", "Recogemiel" },
        { "Frisk", "Cacheo" },
        { "Reckless", "Audaz" },
        { "Multitype", "Multitipo" },
        { "Flower Gift", "Don Floral" },
        { "Bad Dreams", "Mal Sueño" },
        { "Pickpocket", "Hurto" },
        { "Sheer Force", "Potencia Bruta" },
        { "Contrary", "Respondón" },
        { "Unnerve", "Nerviosismo" },
        { "Defiant", "Competitivo" },
        { "Defeatist", "Flaqueza" },
        { "Cursed Body", "Cuerpo Maldito" },
        { "Healer", "Alma Cura" },
        { "Friend Guard", "Compiescolta" },
        { "Weak Armor", "Armadura Frágil" },
        { "Heavy Metal", "Metal Pesado" },
        { "Light Metal", "Metal Liviano" },
        { "Multiscale", "Compensación" },
        { "Toxic Boost", "Ímpetu Tóxico" },
        { "Flare Boost", "Ímpetu Ardiente" },
        { "Harvest", "Cosecha" },
        { "Telepathy", "Telepatía" },
        { "Moody", "Veleta" },
        { "Overcoat", "Funda" },
        { "Poison Touch", "Toque Tóxico" },
        { "Regenerator", "Regeneración" },
        { "Big Pecks", "Sacapecho" },
        { "Sand Rush", "Ímpetu Arena" },
        { "Wonder Skin", "Piel Milagro" },
        { "Analytic", "Cálculo Final" },
        { "Illusion", "Ilusión" },
        { "Imposter", "Impostor" },
        { "Infiltrator", "Allanamiento" },
        { "Mummy", "Momia" },
        { "Moxie", "Autoestima" },
        { "Justified", "Justiciero" },
        { "Rattled", "Cobardía" },
        { "Magic Bounce", "Espejo Mágico" },
        { "Sap Sipper", "Herbívoro" },
        { "Prankster", "Bromista" },
        { "Sand Force", "Poder Arena" },
        { "Iron Barbs", "Punta Acero" },
        { "Zen Mode", "Modo Daruma" },
        { "Victory Star", "Tinovictoria" },
        { "Turboblaze", "Turbollama" },
        { "Teravolt", "Terravoltaje" },
        { "Aroma Veil", "Velo Aroma" },
        { "Flower Veil", "Velo Flor" },
        { "Cheek Pouch", "Carrillo" },
        { "Protean", "Mutatipo" },
        { "Fur Coat", "Pelaje Recio" },
        { "Magician", "Prestidigitador" },
        { "Bulletproof", "Antibalas" },
        { "Competitive", "Tenacidad" },
        { "Strong Jaw", "Mandíbula Fuerte" },
        { "Refrigerate", "Piel Helada" },
        { "Sweet Veil", "Velo Dulce" },
        { "Stance Change", "Cambio Táctico" },
        { "Gale Wings", "Alas Vendaval" },
        { "Mega Launcher", "Megadisparador" },
        { "Grass Pelt", "Manto Frondoso" },
        { "Symbiosis", "Simbiosis" },
        { "Tough Claws", "Garra Dura" },
        { "Pixilate", "Piel Feérica" },
        { "Gooey", "Baba" },
        { "Aerilate", "Piel Celeste" },
        { "Parental Bond", "Amor Filial" },
        { "Dark Aura", "Aura Oscura" },
        { "Fairy Aura", "Aura Feérica" },
        { "Aura Break", "Rompeaura" },
        { "Primordial Sea", "Mar del Albor" },
        { "Desolate Land", "Tierra del Ocaso" },
        { "Delta Stream", "Ráfaga Delta" },
        { "Stamina", "Firmeza" },
        { "Wimp Out", "Huida" },
        { "Emergency Exit", "Retirada" },
        { "Water Compaction", "Hidrorrefuerzo" },
        { "Merciless", "Ensañamiento" },
        { "Shields Down", "Escudo Limitado" },
        { "Stakeout", "Vigilante" },
        { "Water Bubble", "Pompa" },
        { "Steelworker", "Acero Templado" },
        { "Berserk", "Cólera" },
        { "Slush Rush", "Quitanieves" },
        { "Long Reach", "Remoto" },
        { "Liquid Voice", "Voz Fluida" },
        { "Triage", "Primer Auxilio" },
        { "Galvanize", "Piel Eléctrica" },
        { "Surge Surfer", "Cola Surf" },
        { "Schooling", "Banco" },
        { "Disguise", "Disfraz" },
        { "Battle Bond", "Fuerte Afecto" },
        { "Power Construct", "Agrupamiento" },
        { "Corrosion", "Corrosión" },
        { "Comatose", "Letargo Perenne" },
        { "Queenly Majesty", "Regia Presencia" },
        { "Innards Out", "Revés" },
        { "Dancer", "Pareja de Baile" },
        { "Battery", "Batería" },
        { "Fluffy", "Peluche" },
        { "Dazzling", "Cuerpo Vívido" },
        { "Soul-Heart", "Coránima" },
        { "Tangling Hair", "Rizos Rebeldes" },
        { "Receiver", "Receptor" },
        { "Power of Alchemy", "Reacción Química" },
        { "Beast Boost", "Ultraimpulso" },
        { "RKS System", "Sistema Alfa" },
        { "Electric Surge", "Electrogénesis" },
        { "Psychic Surge", "Psicogénesis" },
        { "Misty Surge", "Nebulogénesis" },
        { "Grassy Surge", "Herbogénesis" },
        { "Full Metal Body", "Guardia Metálica" },
        { "Shadow Shield", "Guardia Espectro" },
        { "Prism Armor", "Armadura Prisma" },
        { "Neuroforce", "Fuerza Cerebral" },
        { "Intrepid Sword", "Espada Indómita" },
        { "Dauntless Shield", "Escudo Recio" },
        { "Libero", "Líbero" },
        { "Ball Fetch", "Recogebolas" },
        { "Cotton Down", "Pelusa" },
        { "Propeller Tail", "Hélice Caudal" },
        { "Mirror Armor", "Coraza Reflejo" },
        { "Gulp Missile", "Tragamisil" },
        { "Stalwart", "Acérrimo" },
        { "Steam Engine", "Combustible" },
        { "Punk Rock", "Punk Rock" },
        { "Sand Spit", "Expulsarena" },
        { "Ice Scales", "Escama de Hielo" },
        { "Ripen", "Maduración" },
        { "Ice Face", "Cara de Hielo" },
        { "Power Spot", "Fuente Energía" },
        { "Mimicry", "Mimetismo" },
        { "Screen Cleaner", "Antibarrera" },
        { "Steely Spirit", "Alma Acerada" },
        { "Perish Body", "Cuerpo Mortal" },
        { "Wandering Spirit", "Alma Errante" },
        { "Gorilla Tactics", "Monotema" },
        { "Neutralizing Gas", "Gas Reactivo" },
        { "Pastel Veil", "Velo Pastel" },
        { "Hunger Switch", "Mutapetito" },
        { "Quick Draw", "Mano Rápida" },
        { "Unseen Fist", "Puño Invisible" },
        { "Curious Medicine", "Medicina Extraña" },
        { "Transistor", "Transistor" },
        { "Dragon's Maw", "Mandíbula Dragón" },
        { "Chilling Neigh", "Relincho Blanco" },
        { "Grim Neigh", "Relincho Negro" },
        { "As One", "Unidad Ecuestre" },
        { "Lingering Aroma", "Olor Persistente" },
        { "Seed Sower", "Disemillar" },
        { "Thermal Exchange", "Termoconversión" },
        { "Anger Shell", "Coraza Ira" },
        { "Purifying Salt", "Sal Purificadora" },
        { "Well-Baked Body", "Cuerpo Horneado" },
        { "Wind Rider", "Surcavientos" },
        { "Guard Dog", "Perro Guardián" },
        { "Rocky Payload", "Transportarrocas" },
        { "Wind Power", "Energía Eólica" },
        { "Zero to Hero", "Cambio Heroico" },
        { "Commander", "Comandar" },
        { "Electromorphosis", "Dinamo" },
        { "Protosynthesis", "Paleosíntesis" },
        { "Quark Drive", "Carga Cuark" },
        { "Good as Gold", "Cuerpo Áureo" },
        { "Vessel of Ruin", "Caldero Debacle" },
        { "Sword of Ruin", "Espada Debacle" },
        { "Tablets of Ruin", "Tablilla Debacle" },
        { "Beads of Ruin", "Abalorio Debacle" },
        { "Orichalcum Pulse", "Latido Oricalco" },
        { "Hadron Engine", "Motor Hadrónico" },
        { "Opportunist", "Oportunista" },
        { "Cud Chew", "Rumia" },
        { "Sharpness", "Cortante" },
        { "Supreme Overlord", "General Supremo" },
        { "Costar", "Unísono" },
        { "Toxic Debris", "Capa Tóxica" },
        { "Armor Tail", "Cola Armadura" },
        { "Earth Eater", "Geofagia" },
        { "Mycelium Might", "Poder Fúngico" },
        { "Hospitality", "Hospitalidad" },
        { "Mind's Eye", "Ojo Mental" },
        { "Embody Aspect", "Evocarrecuerdos" },
        { "Toxic Chain", "Cadena Tóxica" },
        { "Supersweet Syrup", "Néctar Dulce" },
        { "Tera Shift", "Teracambio" },
        { "Tera Shell", "Teracaparazón" },
        { "Teraform Zero", "Teraformación 0" },
        { "Poison Puppeteer", "Títere Tóxico" },
    };
}

public static class MovesTranslationDictionary
{
    public static readonly Dictionary<string, string> MovesTranslation = new Dictionary<string, string>
    {
        { "Pound", "Destructor" },
        { "Karate Chop", "Golpe Kárate" },
        { "Double Slap", "Doble Bofetón" },
        { "Comet Punch", "Puño Cometa" },
        { "Mega Punch", "Megapuño" },
        { "Pay Day", "Día de Pago" },
        { "Fire Punch", "Puño Fuego" },
        { "Ice Punch", "Puño Hielo" },
        { "Thunder Punch", "Puño Trueno" },
        { "Scratch", "Arañazo" },
        { "Vise Grip", "Agarre" },
        { "Guillotine", "Guillotina" },
        { "Razor Wind", "Viento Cortante" },
        { "Swords Dance", "Danza Espada" },
        { "Cut", "Corte" },
        { "Gust", "Tornado" },
        { "Wing Attack", "Ataque Ala" },
        { "Whirlwind", "Remolino" },
        { "Fly", "Vuelo" },
        { "Bind", "Atadura" },
        { "Slam", "Atizar" },
        { "Vine Whip", "Látigo Cepa" },
        { "Stomp", "Pisotón" },
        { "Double Kick", "Doble Patada" },
        { "Mega Kick", "Megapatada" },
        { "Jump Kick", "Patada Salto" },
        { "Rolling Kick", "Patada Giro" },
        { "Sand Attack", "Ataque Arena" },
        { "Headbutt", "Golpe Cabeza" },
        { "Horn Attack", "Cornada" },
        { "Fury Attack", "Ataque Furia" },
        { "Horn Drill", "Perforador" },
        { "Tackle", "Placaje" },
        { "Body Slam", "Golpe Cuerpo" },
        { "Wrap", "Constricción" },
        { "Take Down", "Derribo" },
        { "Thrash", "Saña" },
        { "Double-Edge", "Doble Filo" },
        { "Tail Whip", "Látigo" },
        { "Poison Sting", "Picotazo Veneno" },
        { "Twineedle", "Doble Ataque" },
        { "Pin Missile", "Pin Misil" },
        { "Leer", "Malicioso" },
        { "Bite", "Mordisco" },
        { "Growl", "Gruñido" },
        { "Roar", "Rugido" },
        { "Sing", "Canto" },
        { "Supersonic", "Supersónico" },
        { "Sonic Boom", "Bomba Sónica" },
        { "Disable", "Anulación" },
        { "Acid", "Ácido" },
        { "Ember", "Ascuas" },
        { "Flamethrower", "Lanzallamas" },
        { "Mist", "Neblina" },
        { "Water Gun", "Pistola Agua" },
        { "Hydro Pump", "Hidrobomba" },
        { "Surf", "Surf" },
        { "Ice Beam", "Rayo Hielo" },
        { "Blizzard", "Ventisca" },
        { "Psybeam", "Psicorrayo" },
        { "Bubble Beam", "Rayo Burbuja" },
        { "Aurora Beam", "Rayo Aurora" },
        { "Hyper Beam", "Hiperrayo" },
        { "Peck", "Picotazo" },
        { "Drill Peck", "Pico Taladro" },
        { "Submission", "Sumisión" },
        { "Low Kick", "Patada Baja" },
        { "Counter", "Contraataque" },
        { "Seismic Toss", "Sísmico" },
        { "Strength", "Fuerza" },
        { "Absorb", "Absorber" },
        { "Mega Drain", "Megaagotar" },
        { "Leech Seed", "Drenadoras" },
        { "Growth", "Desarrollo" },
        { "Razor Leaf", "Hoja Afilada" },
        { "Solar Beam", "Rayo Solar" },
        { "Poison Powder", "Polvo Veneno" },
        { "Stun Spore", "Paralizador" },
        { "Sleep Powder", "Somnífero" },
        { "Petal Dance", "Danza Pétalo" },
        { "String Shot", "Disparo Demora" },
        { "Dragon Rage", "Furia Dragón" },
        { "Fire Spin", "Giro Fuego" },
        { "Thunder Shock", "Impactrueno" },
        { "Thunderbolt", "Rayo" },
        { "Thunder Wave", "Onda Trueno" },
        { "Thunder", "Trueno" },
        { "Rock Throw", "Lanzarrocas" },
        { "Earthquake", "Terremoto" },
        { "Fissure", "Fisura" },
        { "Dig", "Excavar" },
        { "Toxic", "Tóxico" },
        { "Confusion", "Confusión" },
        { "Psychic", "Psíquico" },
        { "Hypnosis", "Hipnosis" },
        { "Meditate", "Meditación" },
        { "Agility", "Agilidad" },
        { "Quick Attack", "Ataque Rápido" },
        { "Rage", "Furia" },
        { "Teleport", "Teletransporte" },
        { "Night Shade", "Tinieblas" },
        { "Mimic", "Mimético" },
        { "Screech", "Chirrido" },
        { "Double Team", "Doble Equipo" },
        { "Recover", "Recuperación" },
        { "Harden", "Fortaleza" },
        { "Minimize", "Reducción" },
        { "Smokescreen", "Pantalla de Humo" },
        { "Confuse Ray", "Rayo Confuso" },
        { "Withdraw", "Refugio" },
        { "Defense Curl", "Rizo Defensa" },
        { "Barrier", "Barrera" },
        { "Light Screen", "Pantalla de Luz" },
        { "Haze", "Niebla" },
        { "Reflect", "Reflejo" },
        { "Focus Energy", "Foco Energía" },
        { "Bide", "Venganza" },
        { "Metronome", "Metrónomo" },
        { "Mirror Move", "Espejo" },
        { "Self-Destruct", "Autodestrucción" },
        { "Egg Bomb", "Bomba Huevo" },
        { "Lick", "Lengüetazo" },
        { "Smog", "Polución" },
        { "Sludge", "Residuos" },
        { "Bone Club", "Hueso Palo" },
        { "Fire Blast", "Llamarada" },
        { "Waterfall", "Cascada" },
        { "Clamp", "Tenaza" },
        { "Swift", "Meteoros" },
        { "Skull Bash", "Cabezazo" },
        { "Spike Cannon", "Clavo Cañón" },
        { "Constrict", "Restricción" },
        { "Amnesia", "Amnesia" },
        { "Kinesis", "Kinético" },
        { "Soft-Boiled", "Ovocuración" },
        { "High Jump Kick", "Pat. Salto Alta" },
        { "Glare", "Deslumbrar" },
        { "Dream Eater", "Comesueños" },
        { "Poison Gas", "Gas Venenoso" },
        { "Barrage", "Bombardeo" },
        { "Leech Life", "Chupavidas" },
        { "Lovely Kiss", "Beso Amoroso" },
        { "Sky Attack", "Ataque Aéreo" },
        { "Transform", "Transformación" },
        { "Bubble", "Burbuja" },
        { "Dizzy Punch", "Puño Mareo" },
        { "Spore", "Espora" },
        { "Flash", "Destello" },
        { "Psywave", "Psicoonda" },
        { "Splash", "Salpicadura" },
        { "Acid Armor", "Armadura Ácida" },
        { "Crabhammer", "Martillazo" },
        { "Explosion", "Explosión" },
        { "Fury Swipes", "Golpes Furia" },
        { "Bonemerang", "Huesomerang" },
        { "Rest", "Descanso" },
        { "Rock Slide", "Avalancha" },
        { "Hyper Fang", "Hipercolmillo" },
        { "Sharpen", "Afilar" },
        { "Conversion", "Conversión" },
        { "Tri Attack", "Triataque" },
        { "Super Fang", "Superdiente" },
        { "Slash", "Cuchillada" },
        { "Substitute", "Sustituto" },
        { "Struggle", "Forcejeo" },
        { "Sketch", "Esquema" },
        { "Triple Kick", "Triple Patada" },
        { "Thief", "Ladrón" },
        { "Spider Web", "Telaraña" },
        { "Mind Reader", "Telépata" },
        { "Nightmare", "Pesadilla" },
        { "Flame Wheel", "Rueda Fuego" },
        { "Snore", "Ronquido" },
        { "Curse", "Maldición" },
        { "Flail", "Azote" },
        { "Conversion 2", "Conversión2" },
        { "Aeroblast", "Aerochorro" },
        { "Cotton Spore", "Esporagodón" },
        { "Reversal", "Inversión" },
        { "Spite", "Rencor" },
        { "Powder Snow", "Nieve Polvo" },
        { "Protect", "Protección" },
        { "Mach Punch", "Ultrapuño" },
        { "Scary Face", "Cara Susto" },
        { "Feint Attack", "Finta" },
        { "Sweet Kiss", "Beso Dulce" },
        { "Belly Drum", "Tambor" },
        { "Sludge Bomb", "Bomba Lodo" },
        { "Mud-Slap", "Bofetón Lodo" },
        { "Octazooka", "Pulpocañón" },
        { "Spikes", "Púas" },
        { "Zap Cannon", "Electrocañón" },
        { "Foresight", "Profecía" },
        { "Destiny Bond", "Mismo Destino" },
        { "Perish Song", "Canto Mortal" },
        { "Icy Wind", "Viento Hielo" },
        { "Detect", "Detección" },
        { "Bone Rush", "Ataque Óseo" },
        { "Lock-On", "Fijar Blanco" },
        { "Outrage", "Enfado" },
        { "Sandstorm", "Tormenta Arena" },
        { "Giga Drain", "Gigadrenado" },
        { "Endure", "Aguante" },
        { "Charm", "Encanto" },
        { "Rollout", "Rodar" },
        { "False Swipe", "Falso Tortazo" },
        { "Swagger", "Contoneo" },
        { "Milk Drink", "Batido" },
        { "Spark", "Chispa" },
        { "Fury Cutter", "Corte Furia" },
        { "Steel Wing", "Ala de Acero" },
        { "Mean Look", "Mal de Ojo" },
        { "Attract", "Atracción" },
        { "Sleep Talk", "Sonámbulo" },
        { "Heal Bell", "Cascabel Cura" },
        { "Return", "Retribución" },
        { "Present", "Presente" },
        { "Frustration", "Frustración" },
        { "Safeguard", "Velo Sagrado" },
        { "Pain Split", "Divide Dolor" },
        { "Sacred Fire", "Fuego Sagrado" },
        { "Magnitude", "Magnitud" },
        { "Dynamic Punch", "Puño Dinámico" },
        { "Megahorn", "Megacuerno" },
        { "Dragon Breath", "Dragoaliento" },
        { "Baton Pass", "Relevo" },
        { "Encore", "Otra Vez" },
        { "Pursuit", "Persecución" },
        { "Rapid Spin", "Giro Rápido" },
        { "Sweet Scent", "Dulce Aroma" },
        { "Iron Tail", "Cola Férrea" },
        { "Metal Claw", "Garra Metal" },
        { "Vital Throw", "Llave Vital" },
        { "Morning Sun", "Sol Matinal" },
        { "Synthesis", "Síntesis" },
        { "Moonlight", "Luz Lunar" },
        { "Hidden Power", "Poder Oculto" },
        { "Cross Chop", "Tajo Cruzado" },
        { "Twister", "Ciclón" },
        { "Rain Dance", "Danza Lluvia" },
        { "Sunny Day", "Día Soleado" },
        { "Crunch", "Triturar" },
        { "Mirror Coat", "Manto Espejo" },
        { "Psych Up", "Autosugestión" },
        { "Extreme Speed", "Veloc. Extrema" },
        { "Ancient Power", "Poder Pasado" },
        { "Shadow Ball", "Bola Sombra" },
        { "Future Sight", "Premonición" },
        { "Rock Smash", "Golpe Roca" },
        { "Whirlpool", "Torbellino" },
        { "Beat Up", "Paliza" },
        { "Fake Out", "Sorpresa" },
        { "Uproar", "Alboroto" },
        { "Stockpile", "Reserva" },
        { "Spit Up", "Escupir" },
        { "Swallow", "Tragar" },
        { "Heat Wave", "Onda Ígnea" },
        { "Hail", "Granizo" },
        { "Torment", "Tormento" },
        { "Flatter", "Camelo" },
        { "Will-O-Wisp", "Fuego Fatuo" },
        { "Memento", "Legado" },
        { "Facade", "Imagen" },
        { "Focus Punch", "Puño Certero" },
        { "Smelling Salts", "Estímulo" },
        { "Follow Me", "Señuelo" },
        { "Nature Power", "Adaptación" },
        { "Charge", "Carga" },
        { "Taunt", "Mofa" },
        { "Helping Hand", "Refuerzo" },
        { "Trick", "Truco" },
        { "Role Play", "Imitación" },
        { "Wish", "Deseo" },
        { "Assist", "Ayuda" },
        { "Ingrain", "Arraigo" },
        { "Superpower", "Fuerza Bruta" },
        { "Magic Coat", "Capa Mágica" },
        { "Recycle", "Reciclaje" },
        { "Revenge", "Desquite" },
        { "Brick Break", "Demolición" },
        { "Yawn", "Bostezo" },
        { "Knock Off", "Desarme" },
        { "Endeavor", "Esfuerzo" },
        { "Eruption", "Estallido" },
        { "Skill Swap", "Intercambio" },
        { "Imprison", "Sellar" },
        { "Refresh", "Alivio" },
        { "Grudge", "Rabia" },
        { "Snatch", "Robo" },
        { "Secret Power", "Daño Secreto" },
        { "Dive", "Buceo" },
        { "Arm Thrust", "Empujón" },
        { "Camouflage", "Camuflaje" },
        { "Tail Glow", "Luminicola" },
        { "Luster Purge", "Resplandor" },
        { "Mist Ball", "Bola Neblina" },
        { "Feather Dance", "Danza Pluma" },
        { "Teeter Dance", "Danza Caos" },
        { "Blaze Kick", "Patada Ígnea" },
        { "Mud Sport", "Chapoteo Lodo" },
        { "Ice Ball", "Bola Hielo" },
        { "Needle Arm", "Brazo Pincho" },
        { "Slack Off", "Relajo" },
        { "Hyper Voice", "Vozarrón" },
        { "Poison Fang", "Colmillo Veneno" },
        { "Crush Claw", "Garra Brutal" },
        { "Blast Burn", "Anillo Ígneo" },
        { "Hydro Cannon", "Hidrocañón" },
        { "Meteor Mash", "Puño Meteoro" },
        { "Astonish", "Impresionar" },
        { "Weather Ball", "Meteorobola" },
        { "Aromatherapy", "Aromaterapia" },
        { "Fake Tears", "Llanto Falso" },
        { "Air Cutter", "Aire Afilado" },
        { "Overheat", "Sofoco" },
        { "Odor Sleuth", "Rastreo" },
        { "Rock Tomb", "Tumba Rocas" },
        { "Silver Wind", "Viento Plata" },
        { "Metal Sound", "Eco Metálico" },
        { "Grass Whistle", "Silbato" },
        { "Tickle", "Cosquillas" },
        { "Cosmic Power", "Masa Cósmica" },
        { "Water Spout", "Salpicar" },
        { "Signal Beam", "Rayo Señal" },
        { "Shadow Punch", "Puño Sombra" },
        { "Extrasensory", "Paranormal" },
        { "Sky Uppercut", "Gancho Alto" },
        { "Sand Tomb", "Bucle Arena" },
        { "Sheer Cold", "Frío Polar" },
        { "Muddy Water", "Agua Lodosa" },
        { "Bullet Seed", "Semilladora" },
        { "Aerial Ace", "Golpe Aéreo" },
        { "Icicle Spear", "Carámbano" },
        { "Iron Defense", "Defensa Férrea" },
        { "Block", "Bloqueo" },
        { "Howl", "Aullido" },
        { "Dragon Claw", "Garra Dragón" },
        { "Frenzy Plant", "Planta Feroz" },
        { "Bulk Up", "Corpulencia" },
        { "Bounce", "Bote" },
        { "Mud Shot", "Disparo Lodo" },
        { "Poison Tail", "Cola Veneno" },
        { "Covet", "Antojo" },
        { "Volt Tackle", "Placaje Eléc" },
        { "Magical Leaf", "Hoja Mágica" },
        { "Water Sport", "Hidrochorro" },
        { "Calm Mind", "Paz Mental" },
        { "Leaf Blade", "Hoja Aguda" },
        { "Dragon Dance", "Danza Dragón" },
        { "Rock Blast", "Pedrada" },
        { "Shock Wave", "Onda Voltio" },
        { "Water Pulse", "Hidropulso" },
        { "Doom Desire", "Deseo Oculto" },
        { "Psycho Boost", "Psicoataque" },
        { "Roost", "Respiro" },
        { "Gravity", "Gravedad" },
        { "Miracle Eye", "Gran Ojo" },
        { "Wake-Up Slap", "Espabila" },
        { "Hammer Arm", "Machada" },
        { "Gyro Ball", "Giro Bola" },
        { "Healing Wish", "Deseo Cura" },
        { "Brine", "Salmuera" },
        { "Natural Gift", "Don Natural" },
        { "Feint", "Amago" },
        { "Pluck", "Picoteo" },
        { "Tailwind", "Viento Afín" },
        { "Acupressure", "Acupresión" },
        { "Metal Burst", "Represión Metal" },
        { "U-turn", "Ida y Vuelta" },
        { "Close Combat", "A Bocajarro" },
        { "Payback", "Vendetta" },
        { "Assurance", "Buena Baza" },
        { "Embargo", "Embargo" },
        { "Fling", "Lanzamiento" },
        { "Psycho Shift", "Psicocambio" },
        { "Trump Card", "As Oculto" },
        { "Heal Block", "Anticura" },
        { "Wring Out", "Estrujón" },
        { "Power Trick", "Truco Fuerza" },
        { "Gastro Acid", "Bilis" },
        { "Lucky Chant", "Conjuro" },
        { "Me First", "Yo Primero" },
        { "Copycat", "Copión" },
        { "Power Swap", "Cambiafuerza" },
        { "Guard Swap", "Cambiadefensa" },
        { "Punishment", "Castigo" },
        { "Last Resort", "Última Baza" },
        { "Worry Seed", "Abatidoras" },
        { "Sucker Punch", "Golpe Bajo" },
        { "Toxic Spikes", "Púas Tóxicas" },
        { "Heart Swap", "Cambiaalmas" },
        { "Aqua Ring", "Acua Aro" },
        { "Magnet Rise", "Levitón" },
        { "Flare Blitz", "Envite Ígneo" },
        { "Force Palm", "Palmeo" },
        { "Aura Sphere", "Esfera Aural" },
        { "Rock Polish", "Pulimento" },
        { "Poison Jab", "Puya Nociva" },
        { "Dark Pulse", "Pulso Umbrío" },
        { "Night Slash", "Tajo Umbrío" },
        { "Aqua Tail", "Acua Cola" },
        { "Seed Bomb", "Bomba Germen" },
        { "Air Slash", "Tajo Aéreo" },
        { "X-Scissor", "Tijera X" },
        { "Bug Buzz", "Zumbido" },
        { "Dragon Pulse", "Pulso Dragón" },
        { "Dragon Rush", "Carga Dragón" },
        { "Power Gem", "Joya de Luz" },
        { "Drain Punch", "Puño Drenaje" },
        { "Vacuum Wave", "Onda Vacío" },
        { "Focus Blast", "Onda Certera" },
        { "Energy Ball", "Energibola" },
        { "Brave Bird", "Pájaro Osado" },
        { "Earth Power", "Tierra Viva" },
        { "Switcheroo", "Trapicheo" },
        { "Giga Impact", "Gigaimpacto" },
        { "Nasty Plot", "Maquinación" },
        { "Bullet Punch", "Puño Bala" },
        { "Avalanche", "Alud" },
        { "Ice Shard", "Esquirla Helada" },
        { "Shadow Claw", "Garra Umbría" },
        { "Thunder Fang", "Colmillo Rayo" },
        { "Ice Fang", "Colmillo Hielo" },
        { "Fire Fang", "Colmillo Ígneo" },
        { "Shadow Sneak", "Sombra Vil" },
        { "Mud Bomb", "Bomba Fango" },
        { "Psycho Cut", "Psicocorte" },
        { "Zen Headbutt", "Cabezazo Zen" },
        { "Mirror Shot", "Disparo Espejo" },
        { "Flash Cannon", "Foco Resplandor" },
        { "Rock Climb", "Treparrocas" },
        { "Defog", "Despejar" },
        { "Trick Room", "Espacio Raro" },
        { "Draco Meteor", "Cometa Draco" },
        { "Discharge", "Chispazo" },
        { "Lava Plume", "Humareda" },
        { "Leaf Storm", "Lluevahojas" },
        { "Power Whip", "Latigazo" },
        { "Rock Wrecker", "Romperrocas" },
        { "Cross Poison", "Veneno X" },
        { "Gunk Shot", "Lanzamugre" },
        { "Iron Head", "Cabeza de Hierro" },
        { "Magnet Bomb", "Bomba Imán" },
        { "Stone Edge", "Roca Afilada" },
        { "Captivate", "Seducción" },
        { "Stealth Rock", "Trampa Rocas" },
        { "Grass Knot", "Hierba Lazo" },
        { "Chatter", "Cháchara" },
        { "Judgment", "Sentencia" },
        { "Bug Bite", "Picadura" },
        { "Charge Beam", "Rayo Carga" },
        { "Wood Hammer", "Mazazo" },
        { "Aqua Jet", "Acua Jet" },
        { "Attack Order", "Al Ataque" },
        { "Defend Order", "A Defender" },
        { "Heal Order", "Auxilio" },
        { "Head Smash", "Testarazo" },
        { "Double Hit", "Doble Golpe" },
        { "Roar of Time", "Distorsión" },
        { "Spacial Rend", "Corte Vacío" },
        { "Lunar Dance", "Danza Lunar" },
        { "Crush Grip", "Agarrón" },
        { "Magma Storm", "Lluvia Ígnea" },
        { "Dark Void", "Brecha Negra" },
        { "Seed Flare", "Fulgor Semilla" },
        { "Ominous Wind", "Viento Aciago" },
        { "Shadow Force", "Golpe Umbrío" },
        { "Hone Claws", "Afilagarras" },
        { "Wide Guard", "Vasta Guardia" },
        { "Guard Split", "Isoguardia" },
        { "Power Split", "Isofuerza" },
        { "Wonder Room", "Zona Extraña" },
        { "Psyshock", "Psicocarga" },
        { "Venoshock", "Carga Tóxica" },
        { "Autotomize", "Aligerar" },
        { "Rage Powder", "Polvo Ira" },
        { "Telekinesis", "Telequinesis" },
        { "Magic Room", "Zona Mágica" },
        { "Smack Down", "Antiaéreo" },
        { "Storm Throw", "Llave Corsé" },
        { "Flame Burst", "Pirotecnia" },
        { "Sludge Wave", "Onda Tóxica" },
        { "Quiver Dance", "Danza Aleteo" },
        { "Heavy Slam", "Cuerpo Pesado" },
        { "Synchronoise", "Sincrorruido" },
        { "Electro Ball", "Bola Voltio" },
        { "Soak", "Empapar" },
        { "Flame Charge", "Nitrocarga" },
        { "Coil", "Enrosque" },
        { "Low Sweep", "Puntapié" },
        { "Acid Spray", "Bomba Ácida" },
        { "Foul Play", "Juego Sucio" },
        { "Simple Beam", "Onda Simple" },
        { "Entrainment", "Danza Amiga" },
        { "After You", "Cede Paso" },
        { "Round", "Canon" },
        { "Echoed Voice", "Eco Voz" },
        { "Chip Away", "Guardia Baja" },
        { "Clear Smog", "Niebla Clara" },
        { "Stored Power", "Poder Reserva" },
        { "Quick Guard", "Anticipo" },
        { "Ally Switch", "Cambio de Banda" },
        { "Scald", "Escaldar" },
        { "Shell Smash", "Rompecoraza" },
        { "Heal Pulse", "Pulso Cura" },
        { "Hex", "Infortunio" },
        { "Sky Drop", "Caída Libre" },
        { "Shift Gear", "Cambio de Marcha" },
        { "Circle Throw", "Llave Giro" },
        { "Incinerate", "Calcinación" },
        { "Quash", "Último Lugar" },
        { "Acrobatics", "Acróbata" },
        { "Reflect Type", "Clonatipo" },
        { "Retaliate", "Represalia" },
        { "Final Gambit", "Sacrificio" },
        { "Bestow", "Ofrenda" },
        { "Inferno", "Infierno" },
        { "Water Pledge", "Voto Agua" },
        { "Fire Pledge", "Voto Fuego" },
        { "Grass Pledge", "Voto Planta" },
        { "Volt Switch", "Voltiocambio" },
        { "Struggle Bug", "Estoicismo" },
        { "Bulldoze", "Terratemblor" },
        { "Frost Breath", "Vaho Gélido" },
        { "Dragon Tail", "Cola Dragón" },
        { "Work Up", "Avivar" },
        { "Electroweb", "Electrotela" },
        { "Wild Charge", "Voltio Cruel" },
        { "Drill Run", "Taladradora" },
        { "Dual Chop", "Golpe Bis" },
        { "Heart Stamp", "Arrumaco" },
        { "Horn Leech", "Asta Drenaje" },
        { "Sacred Sword", "Espada Santa" },
        { "Razor Shell", "Concha Filo" },
        { "Heat Crash", "Golpe Calor" },
        { "Leaf Tornado", "Ciclón de Hojas" },
        { "Steamroller", "Rodillo de Púas" },
        { "Cotton Guard", "Rizo Algodón" },
        { "Night Daze", "Pulso Noche" },
        { "Psystrike", "Onda Mental" },
        { "Tail Slap", "Plumerazo" },
        { "Hurricane", "Vendaval" },
        { "Head Charge", "Ariete" },
        { "Gear Grind", "Rueda Doble" },
        { "Searing Shot", "Bomba Ígnea" },
        { "Techno Blast", "Tecno Shock" },
        { "Relic Song", "Canto Arcaico" },
        { "Secret Sword", "Sable Místico" },
        { "Glaciate", "Mundo Gélido" },
        { "Bolt Strike", "Ataque Fulgor" },
        { "Blue Flare", "Llama Azul" },
        { "Fiery Dance", "Danza Llama" },
        { "Freeze Shock", "Rayo Gélido" },
        { "Ice Burn", "Llama Gélida" },
        { "Snarl", "Alarido" },
        { "Icicle Crash", "Chuzos" },
        { "V-create", "V de Fuego" },
        { "Fusion Flare", "Llama Fusión" },
        { "Fusion Bolt", "Rayo Fusión" },
        { "Flying Press", "Plancha Voladora" },
        { "Mat Block", "Escudo Tatami" },
        { "Belch", "Eructo" },
        { "Rototiller", "Fertilizante" },
        { "Sticky Web", "Red Viscosa" },
        { "Fell Stinger", "Aguijón Letal" },
        { "Phantom Force", "Golpe Fantasma" },
        { "Trick-or-Treat", "Halloween" },
        { "Noble Roar", "Rugido de Guerra" },
        { "Ion Deluge", "Cortina Plasma" },
        { "Parabolic Charge", "Carga Parábola" },
        { "Forest's Curse", "Condena Silvana" },
        { "Petal Blizzard", "Tormenta Floral" },
        { "Freeze-Dry", "Liofilización" },
        { "Disarming Voice", "Voz Cautivadora" },
        { "Parting Shot", "Última Palabra" },
        { "Topsy-Turvy", "Reversión" },
        { "Draining Kiss", "Beso Drenaje" },
        { "Crafty Shield", "Truco Defensa" },
        { "Flower Shield", "Defensa Floral" },
        { "Grassy Terrain", "Campo de Hierba" },
        { "Misty Terrain", "Campo de Niebla" },
        { "Electrify", "Electrificación" },
        { "Play Rough", "Carantoña" },
        { "Fairy Wind", "Viento Feérico" },
        { "Moonblast", "Fuerza Lunar" },
        { "Boomburst", "Estruendo" },
        { "Fairy Lock", "Cerrojo Feérico" },
        { "King's Shield", "Escudo Real" },
        { "Play Nice", "Camaradería" },
        { "Confide", "Confidencia" },
        { "Diamond Storm", "Torm. Diamantes" },
        { "Steam Eruption", "Chorro de Vapor" },
        { "Hyperspace Hole", "Paso Dimensional" },
        { "Water Shuriken", "Shuriken de Agua" },
        { "Mystical Fire", "Llama Embrujada" },
        { "Spiky Shield", "Barrera Espinosa" },
        { "Aromatic Mist", "Niebla Aromática" },
        { "Eerie Impulse", "Onda Anómala" },
        { "Venom Drench", "Trampa Venenosa" },
        { "Powder", "Polvo Explosivo" },
        { "Geomancy", "Geocontrol" },
        { "Magnetic Flux", "Aura Magnética" },
        { "Happy Hour", "Paga Extra" },
        { "Electric Terrain", "Campo Eléctrico" },
        { "Dazzling Gleam", "Brillo Mágico" },
        { "Celebrate", "Celebración" },
        { "Hold Hands", "Manos Juntas" },
        { "Baby-Doll Eyes", "Ojitos Tiernos" },
        { "Nuzzle", "Moflete Estático" },
        { "Hold Back", "Clemencia" },
        { "Infestation", "Acoso" },
        { "Power-Up Punch", "Puño Incremento" },
        { "Oblivion Wing", "Ala Mortífera" },
        { "Thousand Arrows", "Mil Flechas" },
        { "Thousand Waves", "Mil Temblores" },
        { "Land's Wrath", "Fuerza Telúrica" },
        { "Light of Ruin", "Luz Aniquiladora" },
        { "Origin Pulse", "Pulso Primigenio" },
        { "Precipice Blades", "Filo del Abismo" },
        { "Dragon Ascent", "Ascenso Draco" },
        { "Hyperspace Fury", "Cerco Dimensión" },
        { "Shore Up", "Recogearena" },
        { "First Impression", "Escaramuza" },
        { "Baneful Bunker", "Búnker" },
        { "Spirit Shackle", "Puntada Sombría" },
        { "Darkest Lariat", "Lariat Oscuro" },
        { "Sparkling Aria", "Aria Burbuja" },
        { "Ice Hammer", "Martillo Hielo" },
        { "Floral Healing", "Cura Floral" },
        { "High Horsepower", "Fuerza Equina" },
        { "Strength Sap", "Absorbefuerza" },
        { "Solar Blade", "Cuchilla Solar" },
        { "Leafage", "Follaje" },
        { "Spotlight", "Foco" },
        { "Toxic Thread", "Hilo Venenoso" },
        { "Laser Focus", "Aguzar" },
        { "Gear Up", "Piñón Auxiliar" },
        { "Throat Chop", "Golpe Mordaza" },
        { "Pollen Puff", "Bola de Polen" },
        { "Anchor Shot", "Anclaje" },
        { "Psychic Terrain", "Campo Psíquico" },
        { "Lunge", "Plancha" },
        { "Fire Lash", "Látigo Ígneo" },
        { "Power Trip", "Chulería" },
        { "Burn Up", "Llama Final" },
        { "Speed Swap", "Cambiavelocidad" },
        { "Smart Strike", "Cuerno Certero" },
        { "Purify", "Purificación" },
        { "Revelation Dance", "Danza Despertar" },
        { "Core Enforcer", "Núcleo Castigo" },
        { "Trop Kick", "Patada Tropica" },
        { "Instruct", "Mandato" },
        { "Beak Blast", "Pico Cañón" },
        { "Clanging Scales", "Fragor Escamas" },
        { "Dragon Hammer", "Martillo Dragón" },
        { "Brutal Swing", "Giro Vil" },
        { "Aurora Veil", "Velo Aurora" },
        { "Shell Trap", "Coraza Trampa" },
        { "Fleur Cannon", "Cañón Floral" },
        { "Psychic Fangs", "Psicocolmillo" },
        { "Stomping Tantrum", "Pataleta" },
        { "Shadow Bone", "Hueso Sombrío" },
        { "Accelerock", "Roca Veloz" },
        { "Liquidation", "Hidroariete" },
        { "Prismatic Laser", "Láser Prisma" },
        { "Spectral Thief", "Robasombra" },
        { "Sunsteel Strike", "Meteoimpacto" },
        { "Moongeist Beam", "Rayo Umbrío" },
        { "Tearful Look", "Ojos Llorosos" },
        { "Zing Zap", "Electropunzada" },
        { "Nature's Madness", "Furia Natural" },
        { "Multi-Attack", "Multiataque" },
        { "Mind Blown", "Cabeza Sorpresa" },
        { "Plasma Fists", "Puños Plasma" },
        { "Photon Geyser", "Géiser Fotónico" },
        { "Zippy Zap", "Pikaturbo" },
        { "Splishy Splash", "Salpikasurf" },
        { "Floaty Fall", "Pikapicado" },
        { "Pika Papow", "Pikatormenta" },
        { "Bouncy Bubble", "Vapodrenaje" },
        { "Buzzy Buzz", "Joltioparálisis" },
        { "Sizzly Slide", "Flarembestida" },
        { "Glitzy Glow", "Espeaura" },
        { "Baddy Bad", "Umbreozona" },
        { "Sappy Seed", "Leafitobombas" },
        { "Freezy Frost", "Glaceoprisma" },
        { "Sparkly Swirl", "Sylveotornado" },
        { "Veevee Volley", "Eevimpacto" },
        { "Double Iron Bash", "Ferropuño Doble" },
        { "Max Guard", "Maxibarriera" },
        { "Dynamax Cannon", "Cañón Dinamax" },
        { "Snipe Shot", "Disparo Certero" },
        { "Jaw Lock", "Presa Maxilar" },
        { "Stuff Cheeks", "Atiborramiento" },
        { "No Retreat", "Bastión Final" },
        { "Tar Shot", "Alquitranazo" },
        { "Magic Powder", "Polvo Mágico" },
        { "Dragon Darts", "Dracoflechas" },
        { "Teatime", "Hora del Té" },
        { "Octolock", "Octopresa" },
        { "Bolt Beak", "Electropico" },
        { "Fishious Rend", "Branquibocado" },
        { "Court Change", "Cambio de Cancha" },
        { "Max Flare", "Maxignición" },
        { "Max Flutterby", "Maxinsecto" },
        { "Max Lightning", "Maxitormenta" },
        { "Max Strike", "Maxiataque" },
        { "Max Knuckle", "Maxipuño" },
        { "Max Phantasm", "Maxiespectro" },
        { "Max Hailstorm", "Maxihelada" },
        { "Max Ooze", "Maxiácido" },
        { "Max Geyser", "Maxichorro" },
        { "Max Airstream", "Maxiciclón" },
        { "Max Starfall", "Maxiestela" },
        { "Max Wyrmwind", "Maxidraco" },
        { "Max Mindstorm", "Maxionda" },
        { "Max Rockfall", "Maxilito" },
        { "Max Quake", "Maxitemblor" },
        { "Max Darkness", "Maxisombra" },
        { "Max Overgrowth", "Maxiflora" },
        { "Max Steelspike", "Maximetal" },
        { "Clangorous Soul", "Estruendo Escama" },
        { "Body Press", "Plancha Corporal" },
        { "Decorate", "Decoración" },
        { "Drum Beating", "Batería Asalto" },
        { "Snap Trap", "Cepo" },
        { "Pyro Ball", "Balón Ígneo" },
        { "Behemoth Blade", "Tajo Supremo" },
        { "Behemoth Bash", "Embate Supremo" },
        { "Aura Wheel", "Rueda Aural" },
        { "Breaking Swipe", "Vasto Impacto" },
        { "Branch Poke", "Punzada Rama" },
        { "Overdrive", "Amplificador" },
        { "Apple Acid", "Ácido Málico" },
        { "Grav Apple", "Fuerza G" },
        { "Spirit Break", "Choque Anímico" },
        { "Strange Steam", "Cautivapor" },
        { "Life Dew", "Gota Vital" },
        { "Obstruct", "Obstrucción" },
        { "False Surrender", "Irreverencia" },
        { "Meteor Assault", "Asalto Estelar" },
        { "Eternabeam", "Rayo Infinito" },
        { "Steel Beam", "Metaláser" },
        { "Expanding Force", "Vasta Fuerza" },
        { "Steel Roller", "Allanador Férreo" },
        { "Scale Shot", "Ráfaga Escamas" },
        { "Meteor Beam", "Rayo Meteórico" },
        { "Shell Side Arm", "Moluscañón" },
        { "Misty Explosion", "Bruma Explosiva" },
        { "Grassy Glide", "Fitoimpulso" },
        { "Rising Voltage", "Alto Voltaje" },
        { "Terrain Pulse", "Pulso de Campo" },
        { "Skitter Smack", "Golpe Rastrero" },
        { "Burning Jealousy", "Envidia Ardiente" },
        { "Lash Out", "Desahogo" },
        { "Poltergeist", "Poltergeist" },
        { "Corrosive Gas", "Gas Corrosivo" },
        { "Coaching", "Motivación" },
        { "Flip Turn", "Viraje" },
        { "Triple Axel", "Triple Axel" },
        { "Dual Wingbeat", "Ala Bis" },
        { "Scorching Sands", "Arenas Ardientes" },
        { "Jungle Healing", "Cura Selvática" },
        { "Wicked Blow", "Golpe Oscuro" },
        { "Surging Strikes", "Azote Torrencial" },
        { "Thunder Cage", "Electrojaula" },
        { "Dragon Energy", "Dracoenergía" },
        { "Freezing Glare", "Mirada Heladora" },
        { "Fiery Wrath", "Furia Candente" },
        { "Thunderous Kick", "Patada Relámpago" },
        { "Glacial Lance", "Lanza Glacial" },
        { "Astral Barrage", "Orbes Espectro" },
        { "Eerie Spell", "Conjuro Funesto" },
        { "Dire Claw", "Garra Nociva" },
        { "Psyshield Bash", "Asalto Barrera" },
        { "Power Shift", "Cambiapoder" },
        { "Stone Axe", "Hachazo Pétreo" },
        { "Springtide Storm", "Ciclón Primavera" },
        { "Mystical Power", "Poder Místico" },
        { "Raging Fury", "Erupción de Ira" },
        { "Wave Crash", "Envite Acuático" },
        { "Chloroblast", "Clorofiláser" },
        { "Mountain Gale", "Viento Carámbano" },
        { "Victory Dance", "Danza Triunfal" },
        { "Headlong Rush", "Arremetida" },
        { "Barb Barrage", "Mil Púas Tóxicas" },
        { "Esper Wing", "Ala Aural" },
        { "Bitter Malice", "Rencor Reprimido" },
        { "Shelter", "Retracción" },
        { "Triple Arrows", "Triple Flecha" },
        { "Infernal Parade", "Marcha Espectral" },
        { "Ceaseless Edge", "Tajo Metralla" },
        { "Bleakwind Storm", "Vendaval Gélido" },
        { "Wildbolt Storm", "Electormenta" },
        { "Sandsear Storm", "Simún de Arena" },
        { "Lunar Blessing", "Plegaria Lunar" },
        { "Take Heart", "Bálsamo Osado" },
        { "Tera Blast", "Teraexplosión" },
        { "Silk Trap", "Telatrampa" },
        { "Axe Kick", "Patada Hacha" },
        { "Last Respects", "Homenaje Póstumo" },
        { "Lumina Crash", "Fotocolisión" },
        { "Order Up", "Oído Cocina" },
        { "Jet Punch", "Puño Jet" },
        { "Spicy Extract", "Extracto Picante" },
        { "Spin Out", "Quemarrueda" },
        { "Population Bomb", "Proliferación" },
        { "Ice Spinner", "Pirueta Helada" },
        { "Glaive Rush", "Asalto Espadón" },
        { "Revival Blessing", "Plegaria Vital" },
        { "Salt Cure", "Salazón" },
        { "Triple Dive", "Triple Inmersión" },
        { "Mortal Spin", "Giro Mortífero" },
        { "Doodle", "Decalcomanía" },
        { "Fillet Away", "Deslome" },
        { "Kowtow Cleave", "Genufendiente" },
        { "Flower Trick", "Truco Floral" },
        { "Torch Song", "Canto Ardiente" },
        { "Aqua Step", "Danza Acuática" },
        { "Raging Bull", "Furia Taurina" },
        { "Make It Rain", "Fiebre Dorada" },
        { "Psyblade", "Psicohojas" },
        { "Hydro Steam", "Hidrovapor" },
        { "Ruination", "Calamidad" },
        { "Collision Course", "Nitrochoque" },
        { "Electro Drift", "Electroderrape" },
        { "Shed Tail", "Autotomía" },
        { "Chilly Reception", "Fría Acogida" },
        { "Tidy Up", "Limpieza General" },
        { "Snowscape", "Paisaje Nevado" },
        { "Pounce", "Brinco" },
        { "Trailblaze", "Abrecaminos" },
        { "Chilling Water", "Agua Fría" },
        { "Hyper Drill", "Hipertaladro" },
        { "Twin Beam", "Láser Doble" },
        { "Rage Fist", "Puño Furia" },
        { "Armor Cannon", "Cañón Armadura" },
        { "Bitter Blade", "Espada Lamento" },
        { "Double Shock", "Electropalmas" },
        { "Gigaton Hammer", "Martillo Colosal" },
        { "Comeuppance", "Resarcimiento" },
        { "Aqua Cutter", "Tajo Acuático" },
        { "Blood Moon", "Luna Roja" },
        { "Matcha Gotcha", "Cañón Batidor" },
        { "Syrup Bomb", "Bomba Caramelo" },
        { "Ivy Cudgel", "Garrote Liana" },
        { "Electro Shot", "Electrorrayo" },
        { "Tera Starstorm", "Teraclúster" },
        { "Fickle Beam", "Láser Veleidoso" },
        { "Burning Bulwark", "Llama Protectora" },
        { "Thunderclap", "Relámpago Súbito" },
        { "Mighty Cleave", "Filo Potente" },
        { "Tachyon Cutter", "Tajo Taquión" },
        { "Hard Press", "Prensa Metálica" },
        { "Dragon Cheer", "Bramido Dragón" },
        { "Alluring Voice", "Canto Encantador" },
        { "Temper Flare", "Cólera Ardiente" },
        { "Supercell Slam", "Plancha Voltaica" },
        { "Psychic Noise", "Psicorruido" },
        { "Upper Hand", "Palma Rauda" },
        { "Malignant Chain", "Cadena Virulenta" },
    };
}
